import { test, expect } from '@playwright/test';
test('rapid counting, integrated hand, EV worker, clear and reload', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByTestId('running-count')).toHaveText('0');
  await page.keyboard.press('2'); await page.keyboard.press('3'); await page.keyboard.press('4');
  await expect(page.getByTestId('cards-seen')).toHaveText('3');
  await expect(page.getByTestId('running-count')).toHaveText('+3');
  await page.keyboard.press('Backspace');
  await expect(page.getByTestId('cards-seen')).toHaveText('2');
  await page.keyboard.press('Control+Shift+Z');
  await expect(page.getByTestId('cards-seen')).toHaveText('3');
  await page.keyboard.press('p'); await page.keyboard.press('5'); await page.keyboard.press('6');
  await page.keyboard.press('d'); await page.keyboard.press('6');
  await expect(page.locator('.recommendation h3')).toHaveText('Double down');
  await expect(page.locator('.ev-actions')).toContainText('+0.', { timeout: 10_000 });
  await expect(page.locator('.ev-actions')).not.toContainText('…', { timeout: 10_000 });
  await expect(page.getByTestId('cards-seen')).toHaveText('6');
  await page.getByRole('button', { name: 'Clear current hand' }).click();
  await expect(page.locator('.recommendation h3')).toHaveText('Your next move');
  await expect(page.getByTestId('cards-seen')).toHaveText('6');
  const persistence = await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }));
  expect(persistence).toEqual({ local: 0, session: 0 });
  await page.reload();
  await expect(page.getByTestId('cards-seen')).toHaveText('0');
  await expect(page.getByRole('button', { name: 'Undo last action' })).toBeDisabled();
  expect(errors).toEqual([]);
});
test('rule changes, dynamic chart and small-screen layout', async ({ page }, testInfo) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Table rules', exact: true }).click();
  await page.getByLabel('Dealer soft 17').selectOption('hit');
  await page.getByLabel('Number of decks', { exact: true }).selectOption('2');
  await page.getByLabel('Surrender', { exact: true }).selectOption('none');
  await page.getByRole('button', { name: 'Back to the table' }).click();
  await expect(page.locator('.rules-strip')).toContainText('2 decks');
  await expect(page.locator('.rules-strip')).toContainText('H17');
  await page.getByRole('button', { name: 'Strategy chart', exact: true }).click();
  await page.getByRole('button', { name: 'Soft totals', exact: true }).click();
  await page.getByRole('button', { name: 'A,7 against 2: Double, otherwise Stand', exact: true }).click();
  await expect(page.locator('.cell-explanation')).toContainText('Double');
  await page.getByRole('button', { name: 'Pairs', exact: true }).click();
  await expect(page.locator('.strategy-table tbody tr')).toHaveCount(10);
  await page.getByRole('button', { name: 'Live table', exact: true }).click();
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  await page.screenshot({ path: `/tmp/blackjack-${testInfo.project.name}.png`, fullPage: true });
});
test('already-counted and preview cards do not affect the live counter twice', async ({ page }) => {
  await page.goto('/');
  await page.locator('#bulk-cards').fill('A 10 6');
  await page.getByRole('button', { name: 'Add cards', exact: true }).click();
  await expect(page.getByTestId('cards-seen')).toHaveText('3');
  await page.keyboard.press('p');
  await page.getByLabel('Card registration').selectOption('already');
  await page.getByRole('button', { name: 'Add A to player', exact: true }).click();
  await page.getByRole('button', { name: 'Add 10 to player', exact: true }).click();
  await expect(page.getByTestId('cards-seen')).toHaveText('3');
  await page.keyboard.press('d');
  await page.getByRole('button', { name: 'Add 6 to dealer', exact: true }).click();
  await expect(page.locator('.recommendation h3')).toHaveText('Stand');
  await expect(page.locator('.ev-actions')).toContainText('+1.5000');
  await page.getByRole('button', { name: 'Clear current hand' }).click();
  await page.keyboard.press('p');
  await page.getByLabel('Card registration').selectOption('preview');
  await page.getByRole('button', { name: 'Add 8 to player', exact: true }).click();
  await page.getByRole('button', { name: 'Add 8 to player', exact: true }).click();
  await page.keyboard.press('d'); await page.getByRole('button', { name: 'Add 6 to dealer', exact: true }).click();
  await expect(page.locator('.recommendation h3')).toHaveText('Split');
  await expect(page.getByTestId('cards-seen')).toHaveText('3');
});
test('dealer ace offers pre-peek insurance and main-hand wait state', async ({ page }) => {
  await page.goto('/');
  await page.keyboard.press('p'); await page.keyboard.press('0'); await page.keyboard.press('6');
  await page.keyboard.press('d'); await page.keyboard.press('a');
  await expect(page.locator('.recommendation h3')).toHaveText('Wait for dealer peek');
  await expect(page.locator('.helper-panel')).toContainText('Decline insurance');
  await page.getByRole('button', { name: 'Dealer checked · no blackjack' }).click();
  await expect(page.locator('.recommendation h3')).toHaveText('Surrender');
  await expect(page.locator('.helper-panel')).toContainText('Dealer peek already completed');
});
test('grouped tens, custom tag uncertainty and switching systems retain the shoe', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('checkbox', { name: 'Combine 10s', exact: true }).check();
  await page.keyboard.press('0'); await page.keyboard.press('t');
  await expect(page.getByTestId('cards-seen')).toHaveText('2');
  await expect(page.getByTestId('running-count')).toHaveText('-2');
  await expect(page.locator('.shoe-panel')).toContainText('2 ten-value cards entered without a face');
  await page.locator('.inline-select select').selectOption('Hi-Opt II');
  await expect(page.getByTestId('running-count')).toHaveText('-4');
  await expect(page.getByTestId('cards-seen')).toHaveText('2');
  await page.getByRole('button', { name: 'Table rules', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Counting system', { exact: true }).selectOption('Custom');
  await page.getByLabel('Custom tag J', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Back to the table' }).click();
  await expect(page.getByTestId('running-count')).toHaveText('—');
  await expect(page.locator('.error-banner[role="alert"]')).toContainText('Grouped ten-value cards');
  await page.getByRole('button', { name: 'New shoe' }).click();
  await expect(page.getByTestId('cards-seen')).toHaveText('0');
});
test('all narrow and tablet widths avoid horizontal overflow; large/compact modes work', async ({ page }) => {
  await page.goto('/');
  for (const width of [320, 393, 620, 768, 1000, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), `overflow at ${width}`).toBe(false);
  }
  await page.getByRole('button', { name: 'Table rules', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Compact layout', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Larger card buttons', exact: true }).check();
  await page.getByRole('button', { name: 'Back to the table' }).click();
  await page.setViewportSize({ width: 393, height: 851 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await expect(page.locator('.mobile-livebar')).toBeVisible();
  await page.locator('.mobile-livebar').getByRole('button', { name: 'MY HAND' }).click();
  await expect(page.locator('.input-destination')).toContainText('your hand');
});
