'use client';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { count, betUnits, insurance, cardTag } from '@/lib/blackjack/counting';
import { evaluate, type Action } from '@/lib/blackjack/model';
import { gameActions, gameContext, needsShuffle, ranks, shuffleDeck, type Game, type GameCommand, type PlayingCard } from '@/lib/blackjack/game';
import { basicStrategy, countDeviation, deviationsSupported } from '@/lib/blackjack/strategy';
import { Icon } from './icons';
import { TableSettings, type Preferences } from './table-settings';
import { StrategyChart } from './strategy-chart';
import { useHandEV } from './use-hand-ev';
const NAMES: Record<Action, string> = { hit: 'Hit', stand: 'Stand', double: 'Double', split: 'Split', surrender: 'Surrender' };
const KEYS: Record<Action, string> = { hit: 'H', stand: 'S', double: 'D', split: 'P', surrender: 'R' };
const signed = (n: number, digits = 0) => `${n > 0 ? '+' : ''}${n.toFixed(digits)}`;
const credits = (n: number) => n.toLocaleString('en-GB', { maximumFractionDigits: 2 });
function Card({ card, hidden = false, placeholder = false }: { card?: PlayingCard; hidden?: boolean; placeholder?: boolean }) {
  if (hidden || !card) return <div className={`table-card card-back ${placeholder ? 'placeholder-card' : ''}`} aria-label={hidden ? 'Dealer hole card face down' : 'Waiting for a card'}><span>♠</span></div>;
  const red = card.suit === '♥' || card.suit === '♦';
  return <div className={`table-card ${red ? 'red-suit' : ''}`} aria-label={`${card.rank} ${card.suit}`}><span className="card-corner">{card.rank}<small>{card.suit}</small></span><span className="card-center" aria-hidden="true">{card.suit}</span><span className="card-corner corner-bottom" aria-hidden="true">{card.rank}<small>{card.suit}</small></span></div>;
}
export function GameDashboard({ game, dispatch, prefs, setPrefs, onManual }: { game: Game; dispatch: React.Dispatch<GameCommand>; prefs: Preferences; setPrefs: (preferences: Preferences) => void; onManual: () => void }) {
  const [tab, setTab] = useState<'table' | 'chart'>('table');
  const [bet, setBet] = useState(10);
  const [showCoach, setShowCoach] = useState(true);
  const settings = useRef<HTMLDialogElement>(null);
  const inRound = game.phase === 'player' || game.phase === 'offer';
  const stats = count(game.unseen, game.rules.decks, prefs.system, prefs.custom, prefs.rounding, prefs.estimation, prefs.manual);
  const activeHand = game.hands[game.active];
  const cards = useMemo(() => activeHand ? ranks(activeHand.cards) : [], [activeHand]);
  const context = useMemo(() => gameContext(game), [game]);
  const dealer = game.dealer[0]?.rank;
  const allowed = gameActions(game);
  const base = inRound && dealer ? basicStrategy(cards, dealer, game.rules, context, game.phase === 'player' ? allowed : undefined) : null;
  const index = inRound && dealer && prefs.deviations ? countDeviation(cards, dealer, game.rules, context, prefs.system, prefs.rounding, stats.tc) : null;
  const recommendation = index && allowed.includes(index.action) ? index : base;
  const ev = useHandEV(game.unseen, cards, dealer, game.rules, context, inRound && showCoach);
  const evComplete = game.phase === 'player' && ev && allowed.length > 0 && allowed.every(action => ev.values[action] !== undefined);
  const finiteBest = evComplete ? [...allowed].sort((a, b) => ev!.values[b]! - ev!.values[a]!)[0] : null;
  const insuranceValue = dealer === 'A' ? insurance(game.unseen) : null;
  const betSupported = prefs.system === 'Hi-Lo' && game.rules.decks === 6 && !game.rules.h17 && game.rules.das && game.rules.double === 'any' && game.rules.holeCard === 'peek' && game.rules.surrender !== 'early';
  const suggested = betSupported ? betUnits(stats.rawTC, prefs.spread) : null;
  const reshuffleNext = needsShuffle(game);
  const deal = useCallback(() => dispatch({ type: 'deal', bet, ...(needsShuffle(game) ? { shuffled: shuffleDeck(game.rules.decks) } : {}) }), [game, bet, dispatch]);
  useEffect(() => {
    const keydown = (event: KeyboardEvent) => {
      if (settings.current?.open || (event.target as HTMLElement).closest('input, select, textarea, [contenteditable="true"]') || event.ctrlKey || event.metaKey || event.altKey || event.repeat) return;
      const key = event.key.toUpperCase();
      if (key === ' ' || key === 'ENTER') {
        if ((event.target as HTMLElement).closest('button, a, summary')) return;
        event.preventDefault();
        if (game.phase === 'idle' || game.phase === 'result') deal();
        else if (game.phase === 'offer') dispatch({ type: 'continue' });
        return;
      }
      if (event.shiftKey && key === 'N' && !inRound) { event.preventDefault(); dispatch({ type: 'newShoe' }); return; }
      const action = (Object.keys(KEYS) as Action[]).find(action => KEYS[action] === key);
      if (action && allowed.includes(action)) { event.preventDefault(); dispatch({ type: 'action', action }); }
      if (key === 'I' && game.phase === 'offer' && game.insuranceChoice === 'pending') dispatch({ type: 'insurance', take: true });
    };
    window.addEventListener('keydown', keydown);
    return () => window.removeEventListener('keydown', keydown);
  }, [game.phase, game.insuranceChoice, inRound, allowed, deal, dispatch]);
  return <div className={`app-layout play-workspace ${prefs.compact ? 'compact' : ''} ${prefs.large ? 'large-buttons' : ''}`}>
    <aside className="sidebar"><Link className="brand" href="/" aria-label="Blackjack Trainer home"><span className="brand-mark">♠</span><span>blackjack<span className="brand-secondary">TRAINER</span></span></Link><div className="nav-label">YOUR PRACTICE ROOM</div><nav aria-label="Main navigation"><button className={`nav-button ${tab === 'table' ? 'active' : ''}`} onClick={() => setTab('table')}><Icon name="cards" />Play blackjack<span className="live-dot" /></button><button className="nav-button" onClick={onManual}><Icon name="chart" />Live assistant</button><button className={`nav-button ${tab === 'chart' ? 'active' : ''}`} onClick={() => setTab('chart')}><Icon name="chart" />Strategy chart</button><button className="nav-button" onClick={() => settings.current?.showModal()}><Icon name="settings" />Table rules</button></nav><div className="sidebar-bottom"><div className="privacy-note"><Icon name="shield" /><strong>Practice, at your pace.</strong><p>Virtual credits. No accounts.<br />Your shoe stays in memory.</p></div><a className="creator" href="https://hugosantosribeiro.me" target="_blank" rel="noreferrer">Made by Hugo Santos Ribeiro <span>↗</span></a></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">Workspace <Icon name="chevron" size={13} /><strong>{tab === 'table' ? 'Play blackjack' : 'Strategy chart'}</strong></div><div className="topbar-right"><span className="memory-status"><i />Practice credits only</span><button className="icon-button" aria-label="Game settings" onClick={() => settings.current?.showModal()}><Icon name="settings" /></button></div></header>
      <main className="main-content"><div className="page-heading"><div><div className="eyebrow"><span className="live-dot" /> BLACKJACK · PLAY & LEARN</div><h1>Play the hand. Learn the game.</h1><p>A real shoe, an automatic dealer, and your live strategy coach.</p></div><button className="button secondary reset-button" disabled={inRound} title={inRound ? 'Finish the current round before reshuffling' : 'Reshuffle the cards; keep your practice credits'} onClick={() => dispatch({ type: 'newShoe' })}><Icon name="reset" />New shoe <kbd>⇧ N</kbd></button></div>
        <div className="rules-strip"><span className="rules-label">TABLE RULES</span><span>{game.rules.decks} decks</span><i /><span>{game.rules.h17 ? 'H17' : 'S17'}</span><i /><span>{game.rules.das ? 'DAS' : 'No DAS'}</span><i /><span>{game.rules.holeCard === 'peek' ? 'US · dealer peek' : game.rules.holeCard === 'enhc' ? 'ENHC · all bets' : 'ENHC · OBO'}</span><i /><span>{game.rules.surrender === 'none' ? 'No surrender' : `${game.rules.surrender} surrender`}</span><i /><span>Blackjack pays 3:2</span><button onClick={() => settings.current?.showModal()}>Edit rules <Icon name="settings" size={14} /></button></div>
        {game.error && <div className="error-banner" role="alert"><Icon name="info" /><span>{game.error}</span><button aria-label="Dismiss game error" onClick={() => dispatch({ type: 'dismiss' })}><Icon name="close" /></button></div>}
        {tab === 'chart' ? <StrategyChart rules={game.rules} system={prefs.system} rounding={prefs.rounding} tc={stats.tc} /> : <>
          <div className="practice-stats"><div className="practice-count"><span className="metric-label">TRUE COUNT</span><strong className={stats.tc !== null && stats.tc > 0 ? 'positive' : stats.tc !== null && stats.tc < 0 ? 'negative' : ''} data-testid="game-true-count">{stats.tc === null ? '—' : signed(stats.tc, prefs.rounding === 'none' ? 2 : 0)}</strong><small>{prefs.system} · {prefs.rounding} TC</small></div><div><span className="metric-label">RUNNING COUNT</span><strong data-testid="game-running-count">{signed(stats.rc, Number.isInteger(stats.rc) ? 0 : 1)}</strong><small>{prefs.system === 'KO' ? `Initial ${4 - 4 * game.rules.decks}` : 'Exposed cards only'}</small></div><div><span className="metric-label">CARDS SEEN</span><strong data-testid="game-cards-seen">{stats.seen}</strong><small>{stats.cardsLeft} cards unseen</small></div><div><span className="metric-label">DECKS UNSEEN</span><strong>{stats.exactDecks.toFixed(2)}</strong><small>{stats.penetration.toFixed(1)}% exposed · {game.rules.penetration}% cut</small></div><div className="practice-wallet"><span className="metric-label">PRACTICE BALANCE</span><strong data-testid="game-balance">{credits(game.balance)}</strong><small>Virtual credits <button disabled={inRound} onClick={() => dispatch({ type: 'resetCredits' })}>Reset</button></small></div></div>
          <div className="play-grid"><section className="game-table-panel" aria-label="Playable blackjack table"><div className="table-topline"><span className="pill emerald">{game.phase === 'idle' ? 'READY TO DEAL' : game.phase === 'result' ? 'ROUND COMPLETE' : 'ROUND IN PLAY'}</span><label className="check"><input type="checkbox" checked={showCoach} onChange={e => setShowCoach(e.target.checked)} />Live coach</label></div>
              <div className="felt-table"><div className="dealer-zone"><div className="table-zone-label"><span>DEALER</span><strong>{game.dealer.length ? game.revealed ? `${evaluate(ranks(game.dealer)).total}${evaluate(ranks(game.dealer)).bust ? ' · BUST' : ''}` : `${valueLabel(game.dealer[0])} showing` : game.rules.h17 ? 'Hits soft 17' : 'Stands on all 17s'}</strong></div><div className="table-card-row dealer-cards">{game.dealer.length ? game.dealer.map((card, index) => <Card key={card.id} card={card} hidden={index === 1 && !game.revealed} />) : <><Card placeholder /><Card placeholder /></>}{game.dealer.length === 1 && !game.revealed && <div className="enhc-placeholder"><span>No hole card</span><small>Drawn after your turn</small></div>}</div></div>
                <div className="felt-brand" aria-hidden="true"><span>♠</span> BLACKJACK <small>PAYS 3 TO 2</small></div>
                <div className={`player-zones ${game.hands.length > 1 ? 'split-zones' : ''}`}>{game.hands.length ? game.hands.map((hand, index) => { const score = evaluate(ranks(hand.cards)); const active = game.phase === 'player' && game.active === index; return <div className={`player-zone ${active ? 'active-hand' : ''}`} key={hand.cards[0].id}><div className="table-zone-label"><span>{game.hands.length > 1 ? `HAND ${index + 1}` : 'YOUR HAND'}{active && <i className="live-dot" />}</span><strong>{score.total}<small>{score.soft ? ' soft' : ''}{hand.afterSplit ? ' · split' : ''}</small></strong></div><div className="table-card-row">{hand.cards.map(card => <Card key={card.id} card={card} />)}</div><div className="hand-stake"><span className="mini-chip" />{credits(hand.bet)} credits{hand.result && <span className={`hand-outcome ${hand.net! > 0 ? 'positive' : hand.net! < 0 ? 'negative' : ''}`}>{hand.result} · {signed(hand.net!, hand.net! % 1 ? 1 : 0)}</span>}{!hand.result && hand.status !== 'playing' && <span className="hand-outcome">{hand.status === 'bust' ? 'Bust' : hand.status === 'surrendered' ? 'Surrendered' : 'Stood'}</span>}</div></div>; }) : <div className="player-zone waiting-hand"><div className="table-zone-label"><span>YOUR HAND</span><strong>—</strong></div><div className="table-card-row"><Card placeholder /><Card placeholder /></div><p>Take a seat. The first hand is yours.</p></div>}</div>
              </div>
              <div className={`game-message ${game.phase === 'result' && game.net! > 0 ? 'winning-message' : ''}`} role="status"><span className="live-dot" /><span>{game.message}</span>{game.insuranceBet > 0 && <span className="insurance-stake">Insurance: {credits(game.insuranceBet)}</span>}</div>
              <div className="game-controls">{!inRound ? <><div className="bet-controls"><label>YOUR BET<input aria-label="Practice bet" type="number" step="1" min="1" max={Math.floor(game.balance)} value={bet} onChange={e => setBet(Number(e.target.value))} /></label><div className="bet-chips">{[5, 10, 25, 50, 100].map(amount => <button className={bet === amount ? 'selected' : ''} key={amount} disabled={game.balance < amount} aria-label={`Bet ${amount} credits`} onClick={() => setBet(amount)}>{amount}</button>)}</div><button className="button primary deal-button" disabled={!Number.isInteger(bet) || bet < 1 || bet > game.balance} onClick={deal}>{game.phase === 'result' ? 'Deal next hand' : 'Deal hand'}<Icon name="arrow" size={18} /></button></div><div className="deal-footnote"><span>{reshuffleNext ? 'A fresh shoe will be shuffled before dealing.' : 'Continue from the current shoe.'}</span><span><kbd>Space</kbd> to deal</span></div>{game.balance < 1 && <p className="small muted">Out of credits? Reset the practice balance to keep playing.</p>}</> : game.phase === 'offer' ? <div className="prepeek-controls">{game.insuranceChoice === 'pending' && <><button className="button insurance-button" disabled={game.balance < game.roundBet / 2} onClick={() => dispatch({ type: 'insurance', take: true })}>Take insurance · {credits(game.roundBet / 2)}<kbd>I</kbd></button><button className="button secondary" onClick={() => dispatch({ type: 'insurance', take: false })}>No insurance</button></>}{game.earlyOffer && <button className="button surrender-button" onClick={() => dispatch({ type: 'action', action: 'surrender' })}>Early surrender<kbd>R</kbd></button>}<button className="button primary" onClick={() => dispatch({ type: 'continue' })}>Continue hand<Icon name="arrow" size={16} /></button></div> : <div className="play-actions">{(['hit', 'stand', 'double', 'split', 'surrender'] as Action[]).map(action => <button key={action} className={`play-action ${showCoach && recommendation?.action === action ? 'recommended-action' : ''}`} disabled={!allowed.includes(action)} onClick={() => dispatch({ type: 'action', action })}><span>{NAMES[action]}</span><kbd>{KEYS[action]}</kbd>{showCoach && recommendation?.action === action && <small>COACH PICK</small>}</button>)}</div>}</div>
            </section>
            <aside className="panel play-coach" aria-label="Automatic strategy coach"><div className="panel-heading"><div className="section-title"><Icon name="shield" /><h2>Your live coach</h2></div><span className="pill emerald">AUTO SYNC</span></div><p className="coach-intro">Your cards update the counter automatically. The hidden dealer card stays out until revealed.</p>
              {!showCoach ? <div className="recommendation empty-recommendation"><h3>Trust your read.</h3><p>The game and counts stay live. Turn on “Live coach” to see advice and expected values again.</p></div> : <><div className={`recommendation ${inRound && recommendation ? `action-${recommendation.action}` : 'empty-recommendation'}`} aria-live="polite"><span className="eyebrow">{game.phase === 'offer' ? 'BEFORE THE DEALER CHECK' : index && allowed.includes(index.action) ? 'VALIDATED HI-LO DEVIATION' : 'RULE-DEPENDENT BASIC STRATEGY'}</span><div className="recommendation-action"><h3 data-testid="game-recommendation">{game.phase === 'idle' ? 'Ready when you are.' : game.phase === 'result' ? game.net! > 0 ? 'Nice hand.' : 'Next hand, fresh decision.' : game.phase === 'offer' ? game.earlyOffer && recommendation?.action === 'surrender' ? 'Early surrender' : insuranceValue?.take && prefs.insuranceAlerts ? 'Insurance has positive EV' : 'Continue without insurance' : recommendation ? NAMES[recommendation.action] : 'Finish this hand'}</h3></div><p>{game.phase === 'idle' ? 'Deal your first hand to see the count and the recommended action together.' : game.phase === 'result' ? 'Every revealed card is counted. Deal again to continue learning from the same shoe.' : game.phase === 'offer' ? game.earlyOffer && recommendation?.action === 'surrender' ? 'Giving up half the original bet is preferred before the dealer checks for blackjack.' : 'Insurance is a separate wager. Choose it before the dealer checks; your main hand is resolved afterwards.' : recommendation?.reason}</p>{game.phase === 'player' && recommendation?.conditional && <div className="recommendation-reason">{recommendation.conditional}</div>}</div>
                {game.phase === 'player' && index && allowed.includes(index.action) && base && <div className="basic-comparison"><span>Basic strategy</span><strong>{NAMES[base.action]}</strong><span className="pill gold-pill">Index {signed(index.threshold)}</span></div>}
                {inRound && <div className="ev-section"><div className="ev-heading"><span className="metric-label">FINITE-SHOE EV</span><span className="small muted">Net units / original stake</span></div><div className="ev-actions">{(game.phase === 'offer' ? game.earlyOffer ? ['surrender'] as Action[] : [] : allowed).map(action => <div key={action}><span>{NAMES[action]}</span><strong className={ev?.values[action] !== undefined && ev.values[action]! > 0 ? 'positive' : ''}>{ev?.values[action] !== undefined ? signed(ev.values[action]!, 4) : ev ? 'n/a' : '…'}</strong></div>)}</div>{finiteBest && <div className="composition-decision"><span>Composition-dependent best</span><strong>{NAMES[finiteBest]}</strong></div>}<p className="small muted ev-model">{ev?.error ?? 'Exact remaining shoe, without replacement. Hit uses optimal hit/stand continuation. Split EV is unavailable; heavy calculations have a latency limit.'}</p>{ev && Object.keys(ev.unavailable).length > 0 && <details className="ev-unavailable"><summary>Calculation details</summary>{Object.entries(ev.unavailable).map(([action, reason]) => <p className="small muted" key={action}>{NAMES[action as Action]}: {reason}</p>)}</details>}</div>}</>}
              {game.phase === 'offer' && insuranceValue && <div className="insurance-analysis"><span className="metric-label">INSURANCE · EXACT COMPOSITION</span><strong>{insuranceValue.neutral ? 'Break-even' : insuranceValue.take ? 'Positive EV' : 'Decline insurance'}</strong><p>Ten-value probability {(insuranceValue.probability * 100).toFixed(2)}% · EV {signed(insuranceValue.ev, 4)} per insurance unit.</p></div>}
              <div className="coach-count-system"><label>Counting system<select aria-label="Game counting system" value={prefs.system} onChange={e => setPrefs({ ...prefs, system: e.target.value as Preferences['system'] })}>{['Hi-Lo', 'KO', 'Hi-Opt I', 'Hi-Opt II', 'Omega II', 'Zen Count', 'Custom'].map(system => <option key={system}>{system}</option>)}</select></label><p className="small muted">{deviationsSupported(game.rules, prefs.system, prefs.rounding, context) ? 'Validated six-deck Hi-Lo indices enabled.' : 'Basic strategy active. Hi-Lo indices need six-deck S17/peek/DAS and floor TC.'}</p></div>
              <div className="last-exposure"><span className="metric-label">LAST EXPOSED CARDS</span><div>{game.lastExposed.length ? game.lastExposed.map(card => <span key={card.id}>{card.rank}<small>{signed(cardTag(card.rank, prefs.system, prefs.custom))}</small></span>) : <p className="small muted">Cards appear here as the game reveals them.</p>}</div></div>
              <div className="next-bet-hint"><span className="metric-label">CONFIGURED BET RAMP</span><strong>{suggested === null ? 'Outside configured Hi-Lo scope' : `${suggested} ${suggested === 1 ? 'unit' : 'units'} · ${credits(suggested * prefs.unit)} credits`}</strong><p>User-defined stake schedule; no guaranteed advantage.</p>{!inRound && suggested !== null && <button className="text-button" disabled={game.balance < suggested * prefs.unit} onClick={() => setBet(suggested * prefs.unit)}>Use this bet <Icon name="arrow" size={13} /></button>}</div>
            </aside>
          </div>
          <section className="panel practice-inventory"><div className="panel-heading"><div><h2>The shoe, in real time</h2><p className="small muted">Exact unseen rank inventory. A face-down hole card remains in this population.</p></div><span className="pill">{stats.cardsLeft} unseen</span></div><div className="rank-inventory">{Object.entries(game.unseen).map(([rank, left]) => <div key={rank}><span>{rank}</span><div className="inventory-bar"><i style={{ height: `${left / (game.rules.decks * 4) * 100}%` }} /></div><strong>{left}</strong></div>)}</div>{prefs.aces && <div className="ace-side-count"><span><span className="gold">♠</span> Ace side count</span><strong>{stats.acesSeen} seen <i /> {stats.acesLeft} unseen</strong></div>}</section>
        </>}
        <footer className="page-footer"><span><Icon name="shield" size={14} /> No accounts. No saved games. Refresh starts clean.</span><div><button onClick={onManual}>Track an external game</button><button onClick={() => settings.current?.showModal()}>Rules & shortcuts</button></div></footer>
      </main></div>
    {tab === 'table' && <div className="mobile-livebar" aria-label="Live game overview"><button onClick={() => document.querySelector('.practice-stats')?.scrollIntoView({ behavior: 'smooth', block: 'center' })}><span>TRUE COUNT · RUNNING COUNT</span><strong>{stats.tc === null ? '—' : signed(stats.tc, prefs.rounding === 'none' ? 2 : 0)} <i> / RC {signed(stats.rc, Number.isInteger(stats.rc) ? 0 : 1)}</i></strong></button><button onClick={() => document.querySelector('.game-controls')?.scrollIntoView({ behavior: 'smooth', block: 'center' })}><span>{showCoach ? 'LIVE COACH' : 'YOUR HAND'}</span><strong>{game.phase === 'player' && showCoach && recommendation ? NAMES[recommendation.action] : game.phase === 'offer' ? 'Insurance / continue' : inRound ? 'Your move' : 'Deal next hand'}</strong></button></div>}
    <dialog ref={settings} className="settings-dialog" aria-labelledby="game-settings-title"><div className="dialog-heading"><div><span className="eyebrow">YOUR PRACTICE TABLE</span><h2 id="game-settings-title">Rules & preferences</h2></div><button className="icon-button" aria-label="Close settings" onClick={() => settings.current?.close()}><Icon name="close" /></button></div>{inRound && <p className="rules-locked-note">Finish the current round to edit table rules. Counting preferences remain editable.</p>}<TableSettings rules={game.rules} onRules={rules => dispatch({ type: 'rules', rules })} preferences={prefs} onPreferences={setPrefs} practice rulesLocked={inRound} /><div className="game-shortcuts"><span><kbd>Space</kbd> Deal / continue</span><span><kbd>H</kbd> Hit · <kbd>S</kbd> Stand · <kbd>D</kbd> Double · <kbd>P</kbd> Split · <kbd>R</kbd> Surrender</span><span><kbd>I</kbd> Take insurance · <kbd>⇧ N</kbd> New shoe between rounds</span></div><div className="dialog-footer"><span className="small muted">Practice credits and both shoes stay only in memory.</span><button className="button primary" onClick={() => settings.current?.close()}>Back to the table <Icon name="arrow" size={16} /></button></div></dialog>
  </div>;
}
function valueLabel(card: PlayingCard) { return card.rank; }
