'use client';
import { useState } from 'react';
import { RANKS, type Rules } from '@/lib/blackjack/model';
import { SYSTEMS, type System, type Rounding, type Estimation } from '@/lib/blackjack/counting';
export type Preferences = { system: System; custom: number[]; rounding: Rounding; estimation: Estimation; manual: number; combined: boolean; aces: boolean; insuranceAlerts: boolean; compact: boolean; large: boolean; deviations: boolean; unit: number; spread: number[] };
export const DEFAULT_PREFERENCES: Preferences = { system: 'Hi-Lo', custom: [...SYSTEMS['Hi-Lo']], rounding: 'floor', estimation: 'exact', manual: 6, combined: false, aces: true, insuranceAlerts: true, compact: false, large: false, deviations: true, unit: 10, spread: [1, 1, 2, 4, 6, 8] };
export function TableSettings({ rules, onRules, preferences: p, onPreferences: setP, practice = false, rulesLocked = false }: { rules: Rules; onRules: (rules: Rules) => void; preferences: Preferences; onPreferences: (preferences: Preferences) => void; practice?: boolean; rulesLocked?: boolean }) {
  const [customDecks, setCustomDecks] = useState(String(rules.decks));
  const [error, setError] = useState('');
  const [customSelected, setCustomSelected] = useState(![1, 2, 4, 6, 8].includes(rules.decks));
  const rule = <K extends keyof Rules>(key: K, value: Rules[K]) => onRules({ ...rules, [key]: value });
  const pref = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setP({ ...p, [key]: value });
  return <div className="settings-content">
    <fieldset disabled={rulesLocked}><legend>Table rules <span>Blackjack pays 3:2</span></legend><div className="field-grid">
      <label>Number of decks<select aria-label="Number of decks" value={customSelected ? 'custom' : rules.decks} onChange={e => { setCustomSelected(e.target.value === 'custom'); if (e.target.value !== 'custom') rule('decks', Number(e.target.value)); else setCustomDecks(String(rules.decks)); }}>{[1, 2, 4, 6, 8].map(n => <option value={n} key={n}>{n} decks</option>)}<option value="custom">Custom ({rules.decks} currently)</option></select></label>
      <label>Custom decks (1–32)<div className="input-apply"><input type="number" min="1" max="32" value={customDecks} onChange={e => setCustomDecks(e.target.value)} /><button onClick={() => { const n = Number(customDecks); if (Number.isInteger(n) && n >= 1 && n <= 32) { setError(''); setCustomSelected(![1, 2, 4, 6, 8].includes(n)); rule('decks', n); } else setError('Custom decks must be a whole number from 1 to 32.'); }}>Apply</button></div></label>
      <label>Dealer soft 17<select aria-label="Dealer soft 17" value={rules.h17 ? 'hit' : 'stand'} onChange={e => rule('h17', e.target.value === 'hit')}><option value="stand">Stand on soft 17 (S17)</option><option value="hit">Hit soft 17 (H17)</option></select></label>
      <label>Double restrictions<select aria-label="Double restrictions" value={rules.double} onChange={e => rule('double', e.target.value as Rules['double'])}><option value="any">Any two cards</option><option value="9-11">Hard 9, 10 or 11 only</option><option value="10-11">Hard 10 or 11 only</option></select></label>
      <label>Maximum split hands<select aria-label="Maximum split hands" value={rules.maxHands} onChange={e => rule('maxHands', Number(e.target.value))}>{[1, 2, 3, 4].map(n => <option value={n} key={n}>{n === 1 ? 'No splitting' : `${n} hands`}</option>)}</select></label>
      <label>Surrender<select aria-label="Surrender" value={rules.surrender} onChange={e => rule('surrender', e.target.value as Rules['surrender'])}><option value="none">Not allowed</option><option value="late">Late (after blackjack excluded)</option><option value="early">Early (before blackjack check)</option></select></label>
      <label>Dealer blackjack rule<select aria-label="Dealer blackjack rule" value={rules.holeCard} onChange={e => rule('holeCard', e.target.value as Rules['holeCard'])}><option value="peek">Hole card + peek (US)</option><option value="enhc">No hole card · all bets lost</option><option value="obo">No hole card · original bet only</option></select></label>
      <label>Cut-card penetration: {rules.penetration}%<input type="range" min="25" max="95" step="1" value={rules.penetration} onChange={e => rule('penetration', Number(e.target.value))} /></label>
    </div><div className="check-row"><label className="check"><input type="checkbox" checked={rules.das} onChange={e => rule('das', e.target.checked)} /> Double after split (DAS)</label><label className="check"><input type="checkbox" checked={rules.resplitAces} onChange={e => rule('resplitAces', e.target.checked)} /> Resplit aces</label></div><p className="muted small">{practice ? "Table rules can be changed between rounds and start a fresh shoe. " : "Changing the deck count starts a new shoe. "} Split aces receive one card each; split 21 pays 1:1. ENHC “all bets lost” includes doubles and splits; OBO returns added stakes on dealer blackjack.</p>{error && <p role="alert" className="error-text">{error}</p>}</fieldset>
    <fieldset><legend>Counting preferences</legend><div className="field-grid">
      <label>Counting system<select aria-label="Counting system" value={p.system} onChange={e => pref('system', e.target.value as System)}>{[...Object.keys(SYSTEMS), 'Custom'].map(name => <option key={name}>{name}</option>)}</select></label>
      <label>True count rounding<select aria-label="True count rounding" value={p.rounding} onChange={e => pref('rounding', e.target.value as Rounding)}><option value="floor">Floor (−1.2 → −2)</option><option value="truncate">Truncate (−1.2 → −1)</option><option value="nearest">Nearest (ties toward +∞)</option><option value="none">No rounding</option></select></label>
      <label>Deck estimation<select aria-label="Deck estimation" value={p.estimation} onChange={e => pref('estimation', e.target.value as Estimation)}><option value="exact">Exact cards remaining ÷ 52</option><option value="quarter">Nearest quarter deck</option><option value="half">Nearest half deck</option><option value="whole">Nearest whole deck</option><option value="manual">Manual estimate</option></select></label>
      {p.estimation === 'manual' && <label>Estimated decks remaining<input type="number" min="0.25" max="32" step="0.25" value={p.manual} onChange={e => pref('manual', Math.min(32, Math.max(.25, Number(e.target.value) || .25)))} /></label>}
    </div>{p.system === 'Custom' && <div className="custom-tags">{RANKS.map((rank, i) => <label key={rank}>{rank}<input aria-label={`Custom tag ${rank}`} type="number" min="-10" max="10" step="0.5" value={p.custom[i]} onChange={e => { const custom = [...p.custom]; custom[i] = Math.min(10, Math.max(-10, Number(e.target.value) || 0)); pref('custom', custom); }} /></label>)}</div>}
    <p className="muted small">KO uses its standard initial count (4 − 4 × decks) and running count only. Unbalanced custom systems start at zero and have no TC. Hi-Opt and Omega ace side counts are informational, with no automatic ace adjustment. Hi-Lo deviations are enabled only for the validated six-deck S17/peek/DAS rules, with floor rounding.</p></fieldset>
    <fieldset><legend>Live helpers</legend><div className="check-grid">
      {([['combined', 'Combine 10 / J / Q / K'], ['aces', 'Ace side count'], ['insuranceAlerts', 'Insurance alerts'], ['deviations', 'Validated Hi-Lo deviations'], ['compact', 'Compact layout'], ['large', 'Larger card buttons']] as const).map(([key, label]) => <label className="check" key={key}><input type="checkbox" checked={p[key]} onChange={e => pref(key, e.target.checked)} />{label}</label>)}
    </div><div className="field-grid bet-settings"><label>{practice ? "Base unit (practice credits)" : "Base unit (€)"}<input type="number" min="1" max="100000" value={p.unit} onChange={e => pref('unit', Math.min(100000, Math.max(1, Number(e.target.value) || 1)))} /></label></div>
    <div className="spread-inputs">{p.spread.map((units, i) => <label key={i}>TC {i === 0 ? '≤ 0' : i === 5 ? '≥ 5' : `+${i}`}<div><input aria-label={`Bet units at TC ${i}`} type="number" min="1" max="100" value={units} onChange={e => { const spread = [...p.spread]; spread[i] = Math.min(100, Math.max(1, Number(e.target.value) || 1)); pref('spread', spread); }} /><span>units</span></div></label>)}</div><p className="muted small">The bet ramp uses floor-rounded Hi-Lo TC and assumes 3:2, six decks, S17, peek and DAS. This is a user-defined stake schedule, not a bankroll or profit calculation. It does not guarantee an advantage or profit.</p></fieldset>
    {!practice && <fieldset><legend>Keyboard shortcuts</legend><div className="shortcuts-list"><span><kbd>A</kbd> <kbd>2</kbd>–<kbd>9</kbd> <kbd>0</kbd>/<kbd>T</kbd> <kbd>J</kbd> <kbd>Q</kbd> <kbd>K</kbd> Add card</span><span><kbd>C</kbd> Counter · <kbd>P</kbd> Player · <kbd>D</kbd> Dealer</span><span><kbd>Ctrl</kbd> + <kbd>Z</kbd> Undo · <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Z</kbd> Redo</span><span><kbd>Backspace</kbd> Undo · <kbd>Esc</kbd> Clear hand · <kbd>Shift</kbd> + <kbd>N</kbd> New shoe</span></div></fieldset>}
  </div>;
}
